<CODEGEN_FILENAME>Blobby<StructureName>File.txt</CODEGEN_FILENAME>
;//<REQUIRES_USERTOKEN>FRED</REQUIRES_USERTOKEN>
;//<REQUIRES_USERTOKEN>JOE</REQUIRES_USERTOKEN>
;//<REQUIRES_USERTOKEN>AMY</REQUIRES_USERTOKEN>
;//<OPTIONAL_USERTOKEN>JANET</OPTIONAL_USERTOKEN>
;//<OPTIONAL_USERTOKEN>JEREMY</OPTIONAL_USERTOKEN>
;//<PROCESS_TEMPLATE>aaaaa</PROCESS_TEMPLATE>
;//<PROCESS_TEMPLATE>aaaab</PROCESS_TEMPLATE>
;//<REQUIRES_CUSTOM_TOKEN>MYGENERICTOKEN</REQUIRES_CUSTOM_TOKEN>
;//<REQUIRES_CUSTOM_FIELD_TOKEN>MYFIELDTOKEN</REQUIRES_CUSTOM_FIELD_TOKEN>
;//<PROCESS_TEMPLATE>aaaaa</PROCESS_TEMPLATE>
;//<PROVIDE_FILE>sub.dbl</PROVIDE_FILE>
;//<PROVIDE_FILE>INC:mydef.inc</PROVIDE_FILE>

<ENVIFEXIST:USERNAME>

User tokens: <FRED>, <JOE>, <AMY>

	<FIELD_LOOP>
	<FIELD_NAME>
	</FIELD_LOOP>

<FIELD_LOOP>
<IF FIELD_NAME_LONGER_THAN_10>
<FIELD_NAME_IN_PARENS>
</IF>
</FIELD_LOOP>

-
<KEY_LOOP>
  <SEGMENT_LOOP>
    <IF ALPHA>ALPHA</IF>
  </SEGMENT_LOOP>
</KEY_LOOP>
-

;//<KEY_LOOP><IF MORE>There are more keys!</IF></KEY_LOOP>

;//<FIELD_LOOP><FieldName><||></FIELD_LOOP>

;//  <FIELD_LOOP>
;//    <IF PROMPT>There is a prompt</IF PROMPT>
;//  </FIELD_LOOP>

record <structure_name>:
	<FIELD_LOOP>
	<field_name>, <field_spec> ;<FIELD_DESC>
		<SELECTION_LOOP>	
		- Selection <SELECTION_NUMBER> = <SELECTION_TEXT>
		</SELECTION_LOOP>
	</FIELD_LOOP>
<FIELD_LOOP>							
<field_name>, <field_spec> ;<FIELD_DESC><SELECTION_LOOP> - Selection <SELECTION_NUMBER> = <SELECTION_TEXT></SELECTION_LOOP><IF PROMPT> > Prompt Exists!</IF>
</FIELD_LOOP>

<COUNTER_1_INCREMENT><COUNTER_1_INCREMENT><IF COUNTER_1>Counter 1 has value <COUNTER_1_VALUE> </IF>

These fields have the text FINDME in the user text or long description:
<FIELD_LOOP>
<IF CUSTOM_FINDME>
<FIELD_NAME>
</IF>
</FIELD_LOOP>

<THIS_IS_GARBAGE_AND_SHOULD_BE_LEFT_ALONE>

File addressing is: <FILE_ADDRESSING>


<STRUCTURE_LDESC>
