<CODEGEN_FILENAME><StructureName>.m</CODEGEN_FILENAME>
;//****************************************************************************
;//
;// Title:       oc_class_implementation.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: This template generates an implementation for an Objective-C
;//              data class to represent a Synergy Repository structure.
;//
;// Date:        22nd March 2010
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
/******************************************************************************
 /
 / Title:       <StructureName>.m
 /
 / Author:      <AUTHOR>
 /
 / Company:     <COMPANY>
 /
 /*****************************************************************************
 /
 / WARNING:     This code was generated by CodeGen. Any changes that you make
 /              to this file will be lost if the code is regenerated.
 /
 /*****************************************************************************
*/

#include "<StructureName>.h"

@implementation <StructureName>

//Synthesize property getters and setters
<FIELD_LOOP>
@synthesize <fieldSqlName>;
</FIELD_LOOP>

//Override the dealloc method
-(void)dealloc
{
    //Release any local objects that we have
<FIELD_LOOP>
  <IF OCOBJECT>
    [<fieldSqlName> release];
  </IF>
</FIELD_LOOP>

    //Call our superclass dealloc method
    [super dealloc];
}
@end
