<CODEGEN_FILENAME><structure_name>_xml_file.dbl</CODEGEN_FILENAME>
<PROCESS_TEMPLATE>syn_xml_doc.tpl</PROCESS_TEMPLATE>
;//****************************************************************************
;//
;// Title:       syn_xml_file.tpl
;//
;// Type         CodeGen Template
;//
;// Description: This template generates a Synergy function which creates an
;//              XML file containing the fields of a record.
;//
;// Date:        19th March 2007
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Routine:     <structure_name>_xml_file
;;
;; Author:      <AUTHOR>
;;
;; Company:     <COMPANY>
;;
;;*****************************************************************************
;;
;; WARNING:     This code was generated by CodeGen. Any changes that you make
;;              to this file will be lost if the code is regenerated.
;;
;;*****************************************************************************
;;
function <structure_name>_xml_file ,^val
    .include "<STRUCTURE_NOALIAS>" repository, required in group="<structure_name>"
    optional in a_xml_file, a
    endparams

    .include "DBLDIR:synxml.def"

    stack record localData
        error           ,i4
        xml_doc         ,XML_DOC_TYPE
        xml_file        ,a256
    endrecord

proc

    init localData

    if (^passed(a_xml_file) && a_xml_file) then
        xml_file = a_xml_file
    else
        xml_file = "<structure_name>.xml"

    ;Create an XML document containing the records data
    xml_doc = %<structure_name>_xml_doc(<structure_name>)

    ;Save the XML document to an XML file
    xcall xml_doc_tofile(xml_doc,xml_file)

    ;Delete the XML document
    xcall xml_doc_delete(xml_doc)

    freturn error

endfunction
