<CODEGEN_FILENAME><structure_name>.wsc</CODEGEN_FILENAME>
;//****************************************************************************
;//
;// Title:       tk_input_window.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: This template generates a UI Toolkit script file containing
;//              an input window containing a structures fields.
;//
;// Date:        19th March 2007
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Author:      <AUTHOR>
;;
;; Company:     <COMPANY>
;;
;;*****************************************************************************
;;
;; WARNING:     This code was generated by CodeGen. Any changes that you make
;;              to this file will be lost if the code is regenerated.
;;
;;*****************************************************************************
;
.script
;
.input <STRUCTURE_NAME>, <STRUCTURE_FIELDS>, 78
.border ON, dragbar(ON)
.title "<STRUCTURE_DESC>", top, center
.repository_structure <STRUCTURE_NAME>
<FIELD_LOOP>
<FIELD_TKSCRIPT>
</FIELD_LOOP>
.set ALL, <STRUCTURE_NAME>
.set KEY, <STRUCTURE_NAME>, <PRIMARY_KEY><SEGMENT_LOOP><SEGMENT_NAME><,></SEGMENT_LOOP></PRIMARY_KEY>
.set DATA, <STRUCTURE_NAME>, <DATA_FIELDS_LIST>
.button OK, text("OK"), select("O")
.button CANCEL, text("Cancel"), select("C")
.button_set end
.end

.input <STRUCTURE_NAME>_LUP, 1, 78
.border ON, dragbar(ON)
.title "<STRUCTURE_DESC> Lookup", top, center
.repository_structure <STRUCTURE_NAME>
.field <DISPLAY_FIELD>, pos(1,1), noprompt
.end

.input <STRUCTURE_NAME>_CTA, 10, 60
.border ON, dragbar(ON)
.title "<STRUCTURE_DESC> Criteria", top, center
.repository_structure <STRUCTURE_NAME>
.end
