<CODEGEN_FILENAME>Frm<WindowName>.aspx.vb</CODEGEN_FILENAME>
;//****************************************************************************
;//
;// Title:       vb_webform_codebehind.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to generate the code-behind for a a VB.NET / ASP.NET
;//              2.0 Web From to represent a Synergy repository structure.
;//
;// Date:        22nd October 2007
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
'******************************************************************************
'
' Title:       Frm<WindowName>.aspx.vb
'
' Author:      <AUTHOR>
'
' Company:     <COMPANY>
'
'******************************************************************************
'
' WARNING:     This code was generated by CodeGen. Any changes that you make
'              to this file will be lost if the code is regenerated.
'
'******************************************************************************
'
Partial Class Frm<WindowName>
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

<FIELD_LOOP>
  <IF COMBOBOX>
        If Not IsPostBack Then
            cbo<Field_Sqlname>_load()
        End If

  </IF>
</FIELD_LOOP>
    End Sub

    Protected Sub btnOk_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnOk.Click

    End Sub

    Protected Sub btnCancel_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnCancel.Click

    End Sub

    'Private Sub LoadForm(ByRef objEmployee As Employee)
    '   <FIELD_LOOP>
    '    txt<Field_Sqlname>.Text = obj<Structure_Name>.<Field_Sqlname>
    '   </FIELD_LOOP>
    'End Sub

    'Private Sub UnloadForm(ByRef objEmployee As Employee)
    '   <FIELD_LOOP>
    '    obj<Structure_Name>.<Field_Sqlname> = txt<Field_Sqlname>.Text
    '   </FIELD_LOOP>
    'End Sub

<FIELD_LOOP>
  <IF COMBOBOX>

    Protected Sub cbo<Field_Sqlname>_load()
        Dim Items() As String = Split(<FIELD_SELECTIONS1>, "|")
        For Each Item As String In Items
            cbo<Field_Sqlname>.Items.Add(Item)
        Next
    End Sub
  </IF>
</FIELD_LOOP>

End Class
