<CODEGEN_FILENAME><StructureName>Maint.xaml</CODEGEN_FILENAME>
<PROCESS_TEMPLATE>cs_mvvm_maint_view_code.tpl</PROCESS_TEMPLATE>
;//****************************************************************************
;//
;// Title:       cs_mvvm_maint_view.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to generate C# MVVM View for use in a maintenance
;//              application.
;//
;// Date:        11th December 2009
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
<!--
//*****************************************************************************
//
// File:        <StructureName>Maint.xaml
//
// Description: MVVM Maintenance View for structure <structure_name>
//
// Type:        WPF User Control
//
// Author:      <AUTHOR>
//
// Created:     <DATE> at <TIME>
//
//*****************************************************************************
//
// WARNING:     This code was generated by <CODEGEN_VERSION>. Any changes that
//              you make to this file will be lost if the code is regenerated.
//
//*****************************************************************************
-->
<UserControl x:Class="<MVVM_UI_NAMESPACE>.<StructureName>Maint"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <Grid Margin="10,10,10,10">

        <Grid.RowDefinitions>
            <FIELD_LOOP>
            <RowDefinition Height="30"/>
            </FIELD_LOOP>
            <RowDefinition Height="30"/>
        </Grid.RowDefinitions>

        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>

        <FIELD_LOOP>
        <!-- <FIELD_DESC> -->
        <IF TEXTBOX>
        <TextBlock Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="0" VerticalAlignment="Center"><FIELD_PROMPT></TextBlock>
        <TextBox Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1" Height="22" VerticalAlignment="Center"<IF INFOLINE> ToolTip="<FIELD_INFOLINE>"</IF>
            Text="{Binding Path=<StructureName>Details.<Field_odbcname>}"
            MaxLength="{Binding Path=<StructureName>Details.Max<Field_odbcname>}"/>
        </IF>
        <IF CHECKBOX>
        <CheckBox Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1" VerticalAlignment="Center" IsChecked="{Binding Path=<StructureName>Details.<Field_odbcname>}"<IF INFOLINE>  ToolTip="<FIELD_INFOLINE>"</IF>><FIELD_PROMPT></CheckBox>
        </IF>
        <IF COMBOBOX>
        <IF PROMPT>
        <TextBlock Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="0" VerticalAlignment="Center"><FIELD_PROMPT></TextBlock>
        </IF>
        <ComboBox Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1" SelectedIndex="0" VerticalAlignment="Center"<IF INFOLINE> ToolTip="<FIELD_INFOLINE>"</IF>>
        <SELECTION_LOOP>
            <ComboBoxItem Tag="<SELECTION_VALUE>"><SELECTION_TEXT></ComboBoxItem>
        </SELECTION_LOOP>
        </ComboBox>
        </IF>
        <IF RADIOBUTTONS>
        <IF PROMPT>
        <TextBlock Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="0" VerticalAlignment="Center"><FIELD_PROMPT></TextBlock>
        </IF>
        <StackPanel Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1" VerticalAlignment="Center">
        <SELECTION_LOOP>
            <RadioButton Tag="<SELECTION_VALUE>" VerticalAlignment="Center"<IF INFOLINE> ToolTip="<FIELD_INFOLINE>"</IF><IF FIRST> IsChecked="true"</IF>><SELECTION_TEXT></RadioButton>
        </SELECTION_LOOP>
        </StackPanel>
        </IF>

        </FIELD_LOOP>

        <!-- Buttons -->
        <StackPanel Grid.Row="<STRUCTURE_FIELDS>" Grid.Column="1" Orientation="Horizontal" HorizontalAlignment="Right">
            <Button Height="22" Width="80" VerticalAlignment="Center"
                Command="{Binding Path=SaveData}">OK</Button>
            <Button Height="22" Width="80" VerticalAlignment="Center"
                Command="{Binding Path=CancelChanges}">Cancel</Button>
        </StackPanel>

    </Grid>
</UserControl>
