<CODEGEN_FILENAME><structure_name>_map.dbl</CODEGEN_FILENAME>
;//****************************************************************************
;//
;// Title:       sql_map.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to generate a Synergy subroutine which maps fields in
;//              one record to corresponding fields in another record.  This
;//              template requires that you use an @MAP=STRUCTURE; declaration
;//              in the target structures user text field, and an @MAP=FIELD;
;//              declaration in each of the target structure fields user text
;//              fields.
;//
;// Date:        12th March 2008
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;;*****************************************************************************
;;
;; Routine:     <structure_name>_map
;;
;; Author:      <AUTHOR>
;;
;; Company:     <COMPANY>
;;
;; Created:     <DATE> at <TIME>
;;
;;*****************************************************************************
;;
;; WARNING:     This code was generated by <CODEGEN_VERSION>.  Any changes that
;;              you make to this file will be lost if the code is regenerated.
;;
;;*****************************************************************************
;;
.include "<MAPPED_STRUCTURE>" repository, structure="str<MAPPED_STRUCTURE>", end
.include "<STRUCTURE_NOALIAS>" repository, structure="str<STRUCTURE_NAME>", end

subroutine <structure_name>_map

    required in  <mapped_structure>, str<MAPPED_STRUCTURE>
    required out <structure_name>, str<STRUCTURE_NAME>
    endparams

proc

    ;;Store the record
    <FIELD_LOOP>
    <field_path> = <mapped_path_conv>
    </FIELD_LOOP>

    xreturn

endsubroutine

