<CODEGEN_FILENAME><StructureName>MaintScreen.xaml</CODEGEN_FILENAME>
<REQUIRES_USERTOKEN>MVVM_UI_NAMESPACE</REQUIRES_USERTOKEN>
<PROCESS_TEMPLATE>synnet_mvvm_view_maint_code</PROCESS_TEMPLATE>
<PROCESS_TEMPLATE>synnet_mvvm_global_resources</PROCESS_TEMPLATE>
<PROCESS_TEMPLATE>synnet_mvvm_view_statemanager</PROCESS_TEMPLATE>
<PROCESS_TEMPLATE>synnet_mvvm_vm_maint</PROCESS_TEMPLATE>
;//****************************************************************************
;//
;// Title:       mvvm_view_maint.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Generates a View for use in a simple maintenance program
;//
;// Date:        17th February 2011
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
<!--
;;*****************************************************************************
;;
;; File:        <StructureName>MaintScreen.xaml
;;
;; Description: View class for structure <STRUCTURE_NOALIAS> (XAML)
;;
;; Type:        Class
;;
;; Author:      <AUTHOR>, <COMPANY>
;;
;; Created:     <DATE> at <TIME> by <CODEGEN_VERSION>
;;
;; WRANING:     This code was generated by a tool. Any changes that you make
;;              to this code will be lost if the code is regenerated.
;;
;;*****************************************************************************
-->
<UserControl x:Class="<MVVM_UI_NAMESPACE>.<StructureName>MaintScreen"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:local="clr-namespace:<MVVM_UI_NAMESPACE>"
             local:StateManager.VisualStateProperty="{Binding VisualStateName}"
             mc:Ignorable="d"
             d:DesignHeight="<WINDOW_HEIGHTPX>" d:DesignWidth="<WINDOW_WIDTHPX>">

    <UserControl.Resources>
        <ResourceDictionary Source="GlobalResources.xaml" />
    </UserControl.Resources>

    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="30"/>
        </Grid.RowDefinitions>

        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="VisualStateGroup">
                <VisualState x:Name="EditKeyState">
                    <Storyboard>
<FIELD_LOOP>
<IF NOTPKSEGMENT>
<IF RADIOBUTTONS>
<SELECTION_LOOP>
                        <BooleanAnimationUsingKeyFrames Storyboard.TargetProperty="(UIElement.IsEnabled)" Storyboard.TargetName="fld<FieldSqlName><SELECTION_NUMBER>">
                            <DiscreteBooleanKeyFrame KeyTime="0" Value="False"/>
                        </BooleanAnimationUsingKeyFrames>
</SELECTION_LOOP>
<ELSE>
                        <BooleanAnimationUsingKeyFrames Storyboard.TargetProperty="(UIElement.IsEnabled)" Storyboard.TargetName="fld<FieldSqlName>">
                            <DiscreteBooleanKeyFrame KeyTime="0" Value="False"/>
                        </BooleanAnimationUsingKeyFrames>
</IF RADIOBUTTONS>
</IF NOTPKSEGMENT>
</FIELD_LOOP>
                    </Storyboard>
                </VisualState>
                <VisualState x:Name="EditDataState">
                    <Storyboard>
<FIELD_LOOP>
<IF PKSEGMENT>
                        <BooleanAnimationUsingKeyFrames Storyboard.TargetProperty="(UIElement.IsEnabled)" Storyboard.TargetName="fld<FieldSqlName>">
                            <DiscreteBooleanKeyFrame KeyTime="0" Value="False"/>
                        </BooleanAnimationUsingKeyFrames>
</IF PKSEGMENT>
</FIELD_LOOP>
                    </Storyboard>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>

        <ScrollViewer Grid.Row="0" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto">
        <Grid>

            <Grid.RowDefinitions>
<FIELD_LOOP>
                <RowDefinition/>
</FIELD_LOOP>
            </Grid.RowDefinitions>

            <Grid.ColumnDefinitions>
                <ColumnDefinition/>
                <ColumnDefinition Width="3*"/>
            </Grid.ColumnDefinitions>

<FIELD_LOOP>
<IF PROMPT>
            <Label Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="0"
                     Content="{Binding Path=<StructureName>.<FieldSqlName>Prompt}" />

</IF PROMPT>
<IF TEXTBOX>
            <TextBox x:Name="fld<FieldSqlName>" Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1"
                     Text="{Binding Path=<StructureName>.<FieldSqlName>,ValidatesOnDataErrors=True,UpdateSourceTrigger=PropertyChanged}"
                     MaxLength="{Binding Path=<StructureName>.<FieldSqlName>Length}"
                     ToolTip="{Binding Path=<StructureName>.<FieldSqlName>ToolTip}"
                     Width="<FIELD_PIXEL_WIDTH>"/>
</IF TEXTBOX>
<IF COMBOBOX>
            <ComboBox x:Name="fld<FieldSqlName>" Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1"
                    ToolTip="{Binding Path=<StructureName>.<FieldSqlName>ToolTip}"
                    SelectedIndex="0">
                <SELECTION_LOOP>
                <ComboBoxItem Tag="<SELECTION_VALUE>"><SELECTION_TEXT></ComboBoxItem>
                </SELECTION_LOOP>
            </ComboBox>
</IF COMBOBOX>
<IF CHECKBOX>
            <CheckBox x:Name="fld<FieldSqlName>" Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1"
                IsChecked="{Binding Path=<StructureName>.<FieldSqlName>}"
                ToolTip="{Binding Path=<StructureName>.<FieldSqlName>ToolTip}">
                <FIELD_PROMPT>
            </CheckBox>
</IF CHECKBOX>
<IF RADIOBUTTONS>
            <StackPanel Grid.Row="<FIELD#LOGICAL_ZERO>" Grid.Column="1">
                <SELECTION_LOOP>
                <RadioButton x:Name="fld<FieldSqlName><SELECTION_NUMBER>" Tag="<SELECTION_VALUE>"<IF FIRST> IsChecked="True"</IF>
                    ToolTip="{Binding Path=<StructureName>.<FieldSqlName>ToolTip}" >
                    <SELECTION_TEXT>
                </RadioButton>
                </SELECTION_LOOP>
            </StackPanel>
</IF RADIOBUTTONS>

</FIELD_LOOP>

        </Grid>
        </ScrollViewer>

        <StackPanel Grid.Row="1" Orientation="Horizontal"  HorizontalAlignment="Right">
            <Button Content="OK" Command="{Binding CommandOk}" IsDefault="True" />
            <Button Content="Cancel" Command="{Binding CommandCancel}" />
        </StackPanel>

    </Grid>

</UserControl>

