<CODEGEN_FILENAME><Structure_Name>.vb</CODEGEN_FILENAME>
;//****************************************************************************
;//
;// Title:       vb_class.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to generate a VB data class to represent a Synergy
;//              repository structure.
;//
;// Date:        19th March 2007
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
'******************************************************************************
'
' Title:        <Structure_Name>.vb
'
' Author:       <AUTHOR>
'
' Company:      <COMPANY>
'
' Created:      <DATE> at <TIME>
'
'******************************************************************************
'
' WARNING:      This code was generated by <CODEGEN_VERSION>.  Any changes that
'               you make to this file will be lost if the code is regenerated.
'
'******************************************************************************
'
Public Class <Structure_Name>

    'Private variables
    <FIELD_LOOP>
    Private p_<Field_Sqlname> As <FIELD_VBTYPE>
    </FIELD_LOOP>

    <FIELD_LOOP>
    '<FIELD_DESC>
    Public Property <Field_Sqlname> As <FIELD_VBTYPE>
        Get
            Return p_<Field_Sqlname>
        End Get
        Set
            <IF NUMERIC>
            <IF NOTDATE>
            If ((Value >= <FIELD_MINVALUE>) And (Value <= <FIELD_MAXVALUE>))
                p_<Field_Sqlname> = Value
            Else
                Throw New Exception("Value must be in the range <FIELD_MINVALUE> to <FIELD_MAXVALUE>.")
            End If
            </IF>
            <IF DATE>
            p_<Field_Sqlname> = Value
            </IF>
            </IF>
            <IF NOTNUMERIC>
            p_<Field_Sqlname> = Value
            </IF>
        End Set
    End Property

    </FIELD_LOOP>

End Class
