<CODEGEN_FILENAME>Frm<WindowName>.Designer.vb</CODEGEN_FILENAME>
;//****************************************************************************
;//
;// Title:       vb_winform_codebehind.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to generate the code-behind file for a a VB.NET
;//              Windows From to represent a Synergy repository structure.
;//
;// Date:        30th October 2007
;//
;// Author:      Steve Ives, Synergex Professional Services Group
;//              http://www.synergex.com
;//
;//****************************************************************************
;//
;// Copyright (c) 2012, Synergex International, Inc.
;// All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//

'******************************************************************************
'
' Title:        Frm<WindowName>.Designer.vb
'
' Author:       <AUTHOR>
'
' Company:      <COMPANY>
'
'******************************************************************************
'
' WARNING:      This code was generated by CodeGen. Any changes that you make
'               to this file will be lost if the code is regenerated.
'
'******************************************************************************
'
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Public Partial Class Frm<WindowName>
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

;//
;//============================================================================
;//Instantiate controls
;//
    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()

        <FIELD_LOOP>
        <IF TEXTBOX>
        <IF PROMPT>
        Me.Lbl<Field_sqlname> = New System.Windows.Forms.Label
        </IF>
        Me.Txt<Field_sqlname> = New System.Windows.Forms.TextBox
        <IF DRILL>
        Me.Btn<Field_sqlname> = New System.Windows.Forms.Button
        </IF>
        </IF>
        <IF CHECKBOX>
        Me.Chk<Field_sqlname> = New System.Windows.Forms.CheckBox
        </IF>
        <IF COMBOBOX>
        <IF PROMPT>
        Me.Lbl<Field_sqlname> = New System.Windows.Forms.Label
        </IF>
        Me.Cbo<Field_sqlname> = New System.Windows.Forms.ComboBox
        </IF>
        <IF RADIOBUTTONS>
        'RADIOBUTTONS ARE NOT SUPPORTED YET!
        </IF>
        </FIELD_LOOP>

        Me.ButtonPanel = New System.Windows.Forms.FlowLayoutPanel
        Me.BtnOK = New System.Windows.Forms.Button
        Me.BtnCancel = New System.Windows.Forms.Button

        Me.ButtonPanel.SuspendLayout()
        Me.SuspendLayout()
;//
;//============================================================================
;//Configure controls controls
;//
        <FIELD_LOOP>
;//
;//============================================================================
;//TextBox code
;//
        <IF TEXTBOX>
        <IF PROMPT>

        'Lbl<Field_sqlname>
        Me.Lbl<Field_sqlname>.Name = "Lbl<Field_sqlname>"
        Me.Lbl<Field_sqlname>.Location = New System.Drawing.Point(<PROMPT_PIXEL_COL>,<PROMPT_PIXEL_ROW>)
        Me.Lbl<Field_sqlname>.AutoSize = True
        Me.Lbl<Field_sqlname>.TabIndex = 0
        Me.Lbl<Field_sqlname>.Text = "<FIELD_PROMPT>"
        </IF>

        'Txt<Field_sqlname>
        Me.Txt<Field_sqlname>.Name = "Txt<Field_sqlname>"
        Me.Txt<Field_sqlname>.Location = New System.Drawing.Point(<FIELD_PIXEL_COL>,<FIELD_PIXEL_ROW>)
        Me.Txt<Field_sqlname>.Size = New System.Drawing.Size(<FIELD_PIXEL_WIDTH>,20)
        Me.Txt<Field_sqlname>.TabIndex = <FIELD#LOGICAL>
        Me.Txt<Field_sqlname>.MaxLength = <FIELD_SIZE>
        <IF DISABLED>
        Me.Txt<Field_sqlname>.Enabled = False
        </IF>
        <IF READONLY>
        Me.Txt<Field_sqlname>.ReadOnly = True
        </IF>
        <IF UPPERCASE>
        Me.Txt<Field_sqlname>.CharacterCasing = CharacterCasing.Upper
        </IF>
        <IF REVERSE>
        Me.<Field_sqlname>.BackColor = Color.Black
        Me.<Field_sqlname>.ForeColor = Color.White
        </IF>
        <IF DEFAULT>
        Me.<Field_sqlname>.Text = "<FIELD_DEFAULT>"
        </IF>
        <IF NOECHO>
        Me.<Field_sqlname>.PasswordChar = "*"
        </IF>
        <IF DRILL>

        'Btn<Field_sqlname>
        Me.Btn<Field_sqlname>.Name = "Btn<Field_sqlname>"
        Me.Btn<Field_sqlname>.Location =  New System.Drawing.Point(<FIELD_DRILL_PIXEL_COL>,<FIELD_PIXEL_ROW>)
        Me.Btn<Field_sqlname>.Size = New System.Drawing.Size(24,20)
        Me.Btn<Field_sqlname>.Text = "..."
        </IF>
        </IF>
;//
;//============================================================================
;//CheckBox code
;//
        <IF CHECKBOX>
        '
        'chk<Field_sqlname>
        '
        Me.Chk<Field_sqlname>.Name = "Chk<Field_sqlname>"
        Me.Chk<Field_sqlname>.Location = New System.Drawing.Point(<FIELD_PIXEL_COL>,<FIELD_PIXEL_ROW>)
        Me.Chk<Field_sqlname>.Size = New System.Drawing.Size(<FIELD_PIXEL_WIDTH>, 17)
        Me.Chk<Field_sqlname>.AutoSize = True
        Me.Chk<Field_sqlname>.TabIndex = <FIELD#LOGICAL>
        Me.Chk<Field_sqlname>.UseVisualStyleBackColor = True
        Me.Chk<Field_sqlname>.Text = "<FIELD_PROMPT>"
        <IF DISABLED>
        Me.Chk<Field_sqlname>.Enabled = False
        </IF>
        <IF DEFAULT>
        ;//Me.Chk<Field_sqlname>.Checked = True
        ;//Me.Chk<Field_sqlname>.CheckState = System.Windows.Forms.CheckState.Checked
        </IF>
        </IF>
;//
;//============================================================================
;//ComboBox code
;//
        <IF COMBOBOX>
        <IF PROMPT>
        '
        'lbl<Field_sqlname>
        '
        Me.Lbl<Field_sqlname>.Name = "Lbl<Field_sqlname>"
        Me.Lbl<Field_sqlname>.Location = New System.Drawing.Point(<PROMPT_PIXEL_COL>,<PROMPT_PIXEL_ROW>)
        Me.Lbl<Field_sqlname>.AutoSize = True
        Me.Lbl<Field_sqlname>.TabIndex = 0
        Me.Lbl<Field_sqlname>.Text = "<FIELD_PROMPT>"
        </IF>
        '
        'cbo<Field_sqlname>
        '
        Me.Cbo<Field_sqlname>.Name = "Cbo<Field_sqlname>"
        Me.Cbo<Field_sqlname>.Location = New System.Drawing.Point(<FIELD_PIXEL_COL>,<FIELD_PIXEL_ROW>)
        Me.Cbo<Field_sqlname>.Size = New System.Drawing.Size(<FIELD_PIXEL_WIDTH>, 21)
        Me.Cbo<Field_sqlname>.TabIndex = <FIELD#LOGICAL>
        Me.Cbo<Field_sqlname>.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.Cbo<Field_sqlname>.FormattingEnabled = True
        <IF DISABLED>
        Me.Cbo<Field_sqlname>.Enabled = False
        </IF>
        Me.Cbo<Field_sqlname>.Items.AddRange(getComboItems(<FIELD_SELECTIONS1>))
        </IF>
;//
;//============================================================================
;//RadioButtons code
;//
        <IF RADIOBUTTONS>
        '
        'rb<Field_sqlname>
        '
        'RADIOBUTTONS ARE NOT SUPPORTED YET!
        </IF>
;//
;//============================================================================
;//Configure controls and form
;//
        </FIELD_LOOP>

        'ButtonPanel
        Me.ButtonPanel.Controls.Add(Me.BtnCancel)
        Me.ButtonPanel.Controls.Add(Me.BtnOK)
        Me.ButtonPanel.Dock = System.Windows.Forms.DockStyle.Bottom
        Me.ButtonPanel.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
        Me.ButtonPanel.Location = New System.Drawing.Point(0, 476)
        Me.ButtonPanel.Name = "ButtonPanel"
        Me.ButtonPanel.Size = New System.Drawing.Size(792, 30)
        Me.ButtonPanel.TabIndex = 100

        'BtnOK
        Me.BtnOK.Name = "BtnOK"
        Me.BtnOK.Text = "&OK"
        Me.BtnOK.TabIndex = 101

        'BtnCancel
        Me.BtnCancel.Name = "BtnCancel"
        Me.BtnCancel.Text = "&Cancel"
        Me.BtnCancel.TabIndex = 102
        Me.BtnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel

        'Frm<WindowName>
        Me.Name = "Frm<WindowName>"
        Me.Text = "<STRUCTURE_DESC> Maintenance"
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(<WINDOW_WIDTHPX>, <WINDOW_HEIGHTPX>)
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog
        Me.MaximizeBox = False
        Me.MinimizeBox = False

        Me.Controls.Add(Me.ButtonPanel)
        <FIELD_LOOP>
        <IF TEXTBOX>
        <IF PROMPT>
        Me.Controls.Add(Me.Lbl<Field_sqlname>)
        </IF>
        Me.Controls.Add(Me.Txt<Field_sqlname>)
        <IF DRILL>
        Me.Controls.Add(Me.Btn<Field_sqlname>)
        </IF>
        </IF>
        <IF CHECKBOX>
        Me.Controls.Add(Me.Chk<Field_sqlname>)
        </IF>
        <IF COMBOBOX>
        <IF PROMPT>
        Me.Controls.Add(Me.Lbl<Field_sqlname>)
        </IF>
        Me.Controls.Add(Me.Cbo<Field_sqlname>)
        </IF>
        <IF RADIOBUTTONS>
        ;RADIOBUTTONS ARE NOT SUPPORTED YET!
        </IF>
        </FIELD_LOOP>

        Me.AcceptButton = Me.BtnOK
        Me.CancelButton = Me.BtnCancel

        Me.ButtonPanel.ResumeLayout(False)
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

;//
;//============================================================================
;//Declare object variables for controls
;//
    <FIELD_LOOP>
    <IF TEXTBOX>
    <IF PROMPT>
    Friend WithEvents Lbl<Field_sqlname> As System.Windows.Forms.Label
    </IF>
    Friend WithEvents Txt<Field_sqlname> As System.Windows.Forms.TextBox
    <IF DRILL>
    Friend WithEvents Btn<Field_sqlname> As System.Windows.Forms.Button
    </IF>
    </IF>
    <IF CHECKBOX>
    Friend WithEvents Chk<Field_sqlname> As System.Windows.Forms.CheckBox
    </IF>
    <IF COMBOBOX>
    <IF PROMPT>
    Friend WithEvents Lbl<Field_sqlname> As System.Windows.Forms.Label
    </IF>
    Friend WithEvents Cbo<Field_sqlname> As System.Windows.Forms.ComboBox
    </IF>
    <IF RADIOBUTTONS>
    'RADIOBUTTONS ARE NOT SUPPORTED YET!
    </IF>
    </FIELD_LOOP>
    Friend WithEvents ButtonPanel as System.Windows.Forms.FlowLayoutPanel
    Friend WithEvents BtnOK As System.Windows.Forms.Button
    Friend WithEvents BtnCancel As System.Windows.Forms.Button

End Class
