<CODEGEN_FILENAME><Structure_name>_Content.CodeGen.xaml</CODEGEN_FILENAME>
<REQUIRES_USERTOKEN>ASSEMBLYNAME</REQUIRES_USERTOKEN>
;//****************************************************************************
;//
;// Title:       Symphony_Content.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to define selection objects for combo boc style fields.
;//
;// Author:      Richard C. Morris, Synergex Professional Services Group
;//
;// Copyright (c) 2012, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;//****************************************************************************
<!--
 WARNING: This code was generated by CodeGen. Any changes that you
          make to this code will be overwritten if the code is regenerated!

 Template author:	Richard C. Morris, Synergex Professional Services Group

 Template Name:	Symphony Framework : <TEMPLATE>.tpl

-->

<!-- converter resources -->
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	xmlns:content="clr-namespace:<NAMESPACE>;assembly=<ASSEMBLYNAME>">

    <!-- create some local data objects for combo controls -->

	<SYMPHONY_CLEARCONTENTLIST>
	<FIELD_LOOP>
	<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
	<IF SELECTIONS>
	<IF NOTRADIOBUTTONS>
	  <SYMPHONY_CONTENTLISTFROMFIELD>
	</IF NOTRADIOBUTTONS>
	</IF SELECTIONS>
	<IF SELWND>
	  <SYMPHONY_CONTENTLISTFROMWINDOW>
	</IF SELWND>
	</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
	</FIELD_LOOP>
	<SYMPHONY_CLEARCONTENTLIST>
</ResourceDictionary>

