<CODEGEN_FILENAME><Structure_name>_DataView.CodeGen.xaml</CODEGEN_FILENAME>
<REQUIRES_USERTOKEN>ASSEMBLYNAME</REQUIRES_USERTOKEN>
<PROCESS_TEMPLATE>Symphony_DataView_code</PROCESS_TEMPLATE>
<OPTIONAL_USERTOKEN>DATABINDING=MasterData</OPTIONAL_USERTOKEN>
;//****************************************************************************
;//
;// Title:       Symphony_DataView.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template that defines all the fields within a structure into the data view
;//
;// Author:      Richard C. Morris, Synergex Professional Services Group
;//
;// Copyright (c) 2012, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;//****************************************************************************
<!--
 WARNING: This code was generated by CodeGen. Any changes that you
          make to this code will be overwritten if the code is regenerated!

 Template author:	Richard C. Morris, Synergex Professional Services Group

 Template Name:	Symphony Framework : <TEMPLATE>.tpl

-->
<UserControl x:Class="<NAMESPACE>.<Structure_name>_DataView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:symphonyControls="clr-namespace:Symphony.Conductor.Controls;assembly=SymphonyConductor"
             mc:Ignorable="d"
             d:DesignHeight="600" d:DesignWidth="1100">

    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
			<ResourceDictionary Source="pack://application:,,,/SymphonyConductor;component/Resources/Styles.xaml"/>
			<ResourceDictionary Source="pack://application:,,,/SymphonyConductor;component/Resources/Converters.xaml"/>
            <ResourceDictionary Source="pack://application:,,,/<ASSEMBLYNAME>;component/Resources/<Structure_name>_Content.CodeGen.xaml"/>
            <ResourceDictionary Source="pack://application:,,,/<ASSEMBLYNAME>;component/Resources/<Structure_name>_style.CodeGen.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>


    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"></RowDefinition>
        </Grid.RowDefinitions>

		<ScrollViewer Grid.Row="0">
			<Grid>
				<Grid.RowDefinitions>
<FIELD_LOOP>
<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
<IF LANGUAGE>
<IF TOOLKIT>
<IF REPORT>
					<RowDefinition Height="auto"/>
</IF REPORT>
</IF TOOLKIT>
</IF LANGUAGE>
</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
</FIELD_LOOP>
				</Grid.RowDefinitions>
;//
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="auto" />
					<ColumnDefinition Width="auto" />
					<ColumnDefinition Width="*" />
				</Grid.ColumnDefinitions>
<SYMPHONY_LOOPSTART>
<FIELD_LOOP>
<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
<IF LANGUAGE>
<IF TOOLKIT>
<IF REPORT>
				<IF NOCHECKBOX>
				<Label Grid.Row="<SYMPHONY_LOOPVALUE>" Grid.Column="0"
					   Style="{StaticResource <Structure_name>_<Field_sqlname>_prompt}" DataContext="{Binding Path=<DATABINDING>}" />
				</IF NOCHECKBOX>
				<symphonyControls:FieldControl Grid.Row="<SYMPHONY_LOOPVALUE>" Grid.Column="1"
					DataContext="{Binding Path=<DATABINDING>}"
					Style="{StaticResource <Structure_name>_<Field_sqlname>_style}">
				</symphonyControls:FieldControl>
<IF ALPHA>
				<TextBlock Grid.Row="<SYMPHONY_LOOPVALUE>" Grid.Column="2"
					   Text="{Binding Path=<DATABINDING>.<Field_sqlname>, Converter={StaticResource alphaConverter}}" />
</IF ALPHA>

<IF DECIMAL>
<IF PRECISION>
				<TextBlock Grid.Row="<SYMPHONY_LOOPVALUE>" Grid.Column="2"
					   Text="{Binding Path=<DATABINDING>.<Field_sqlname>, Converter={StaticResource impliedDecimalConverter}}" />
<ELSE>
				<TextBlock Grid.Row="<SYMPHONY_LOOPVALUE>" Grid.Column="2"
					   Text="{Binding Path=<DATABINDING>.<Field_sqlname>, Converter={StaticResource decimalConverter}}" />
</IF>
</IF DECIMAL>
<IF DATE_YYYYMMDD>
				<TextBlock Grid.Row="<SYMPHONY_LOOPVALUE>" Grid.Column="2"
					   Text="{Binding Path=<DATABINDING>.<Field_sqlname>, Converter={StaticResource decimalConverter}}" />
</IF DATE_YYYYMMDD>

<SYMPHONY_LOOPINCREMENT>
</IF REPORT>
</IF TOOLKIT>
</IF LANGUAGE>
</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
</FIELD_LOOP>
			</Grid>
		</ScrollViewer>

    </Grid>

</UserControl>
