<CODEGEN_FILENAME>MainWindow1.xaml.dbl</CODEGEN_FILENAME>
<REQUIRES_USERTOKEN>VIEWMODELNAMESPACE</REQUIRES_USERTOKEN>
;//****************************************************************************
;//
;// Title:       Symphony_CRUDMainWindow_code.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to provide CRUD main window view code behind
;//
;// Author:      Richard C. Morris, Synergex Professional Services Group
;//
;// Copyright (c) 2012, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;//****************************************************************************
;;****************************************************************************
;;
;; WARNING: This code was generated by CodeGen. Any changes that you
;;          make to this code will be overwritten if the code is regenerated!
;;
;; Template author:	Richard C. Morris, Synergex Professional Services Group
;;
;; Template Name:	Symphony Framework : <TEMPLATE>.tpl
;;
;;****************************************************************************
import System
import System.Collections
import System.Collections.Generic
import System.Diagnostics
import System.Text
import System.Windows
import System.Windows.Controls
import System.Windows.Data
import System.Windows.Documents
import System.Windows.Input
import System.Windows.Shapes
import System.Windows.Media
import System.Windows.Media.Imaging
import System.Windows.Navigation


namespace <NAMESPACE>

	public partial class MainWindow1 extends Window

		public method MainWindow1
			endparams
		proc
			try
			begin
				this.InitializeComponent()
			end
			catch (e, @Exception)
			begin
				Symphony.Core.DebugView.WriteException(e)
				this.Close()
			end
			endtry
		endmethod

		private method Window_Loaded, void
			sender, @object
			e, @System.Windows.RoutedEventArgs
			endparams
		proc
			try
			begin
				this.DataContext = new <VIEWMODELNAMESPACE>.<Structure_name>_CRUDViewModel(this)
			end
			catch (e, @Exception)
			begin
				Symphony.Core.DebugView.WriteException(e)
				this.Close()
			end
			endtry
		endmethod

	endclass
endnamespace

